### ISSUE TITLE
Change required synchronization level

### ISSUE THREAD

**Issue by ssaamm** [virtualramblas/publishtokafka-plugin#6]
Hi there,

What's the reasoning behind [requiring `BuildStepMonitor.STEP`](https://github.com/virtualramblas/publishtokafka-plugin/blob/343618912872107dff0c3b1bed3572c2877efd27/src/main/java/ie/googlielmo/publishtokafka/PublishToKafkaBuilder.java#L411-L414)? It seems like this wouldn't need synchronization, and could use `BuildStepMonitor.NONE` ([`getRequiredMonitorService` javadoc](http://hudson-ci.org/javadoc/hudson/tasks/BuildStep.html#getRequiredMonitorService())).

Thanks!

**Comment by virtualramblas** [comment]
Hi Sam,

Thanks a lot for your feedback.
The reason for using BuildStepMonitor.STEP is due to compatibility with earlier Jenkins versions. No particular reason to use that value when installing and running the plugin in latest releases. What I will do in the next release of the plugin is to add a further configuration parameter to allow users to choose between NONE (default), STEP and BUILD. It would be available next week.

Best Regards,
Guglielmo

**Comment by ssaamm** [comment]
Hi Guglielmo,

Realized I forgot to tell you thanks for working on this plugin! It's helpful to me.

Anyway, I very well may be missing something, but this line from the docs makes it seem like it's perfectly safe to return `NONE`, as I don't think this plugin depends on anything from a previous build.

> If your build step doesn't use anything from a previous build (for example, if you don't even call Run#getPreviousBuild()), then you can return BuildStepMonitor.NONE without making further code changes and you are done with migration. ([docs](http://hudson-ci.org/javadoc/hudson/tasks/BuildStep.html#getRequiredMonitorService%28%29))

**Comment by virtualramblas** [comment]
Change request completed.
